-- 0001: Esquema base (contrato del codigo v1 + tablas de la fase 2).

-- 1. USUARIO --------------------------------------------------
create table public.usuario (
    usuario_id   bigint generated always as identity primary key,
    auth_uid     uuid unique references auth.users (id) on delete set null,
    nombre       varchar(100) not null,
    apellido     varchar(100) not null default '',
    email        varchar(255) unique,
    telefono     varchar(25),
    tipo_usuario varchar(20)  not null default 'Alumno'
        constraint ck_usuario_tipo
        check (tipo_usuario in ('Alumno','Maestro','Administrativo','Soporte','Administrador')),
    activo       boolean not null default true,
    creado_at    timestamptz not null default now()
);
comment on table public.usuario is
    'Perfil de aplicacion, vinculado 1:1 con auth.users via auth_uid (trigger en 0004).';

-- 2. CATALOGO -------------------------------------------------
-- "by default" (no ALWAYS): la semilla inserta IDs explicitos que el frontend hardcodea.
create table public.catalogo (
    catalogo_id bigint generated by default as identity primary key,
    tipo        varchar(50) not null
        constraint ck_catalogo_tipo
        check (tipo in ('categoria','area','estado','prioridad')),
    nombre      varchar(100) not null,
    codigo      text,   -- catalog-service y los embeds de prioridad la seleccionan
    orden       int,
    nivel       int,
    constraint uq_catalogo_tipo_nombre unique (tipo, nombre)
);
comment on table public.catalogo is
    'Tabla maestra: categorias, areas, estados y prioridades. IDs <= 100 reservados a la semilla.';

-- 3. TICKET ---------------------------------------------------
create table public.ticket (
    ticket_id             bigint generated always as identity primary key,
    titulo                varchar(255) not null,
    detalles              text not null
        constraint ck_ticket_detalles_len check (char_length(detalles) <= 5000),
    fecha_creacion        timestamptz not null default now(),
    fecha_cierre          timestamptz,
    eta_estimada          timestamptz,  -- fase 2: fecha_creacion + horas del SLA
    reportador_id         bigint not null,
    categoria_id          bigint not null,
    prioridad_id          bigint not null,
    estado_id             bigint not null,
    area_notificada_id    bigint not null,
    maestro_notificado_id bigint,       -- asignado actual (la v1 lo usa en vez de ASIGNACION)
    -- FKs obligatorias: los embeds de PostgREST solo se resuelven via FK.
    constraint fk_ticket_reportador foreign key (reportador_id)         references public.usuario  (usuario_id),
    constraint fk_ticket_categoria  foreign key (categoria_id)          references public.catalogo (catalogo_id),
    constraint fk_ticket_prioridad  foreign key (prioridad_id)          references public.catalogo (catalogo_id),
    constraint fk_ticket_estado     foreign key (estado_id)             references public.catalogo (catalogo_id),
    constraint fk_ticket_area       foreign key (area_notificada_id)    references public.catalogo (catalogo_id),
    constraint fk_ticket_asignado   foreign key (maestro_notificado_id) references public.usuario  (usuario_id)
);
comment on table public.ticket is 'Incidencia reportada; registro principal del sistema.';

create index idx_ticket_reportador on public.ticket (reportador_id);
create index idx_ticket_estado     on public.ticket (estado_id);
create index idx_ticket_fecha      on public.ticket (fecha_creacion desc);

-- 4. ADJUNTO --------------------------------------------------
create table public.adjunto (
    adjunto_id       bigint generated always as identity primary key,
    ticket_id        bigint not null references public.ticket (ticket_id) on delete cascade,
    subido_por_id    bigint not null references public.usuario (usuario_id),
    nombre_archivo   varchar(255) not null,
    ruta_archivo_url varchar(1024) not null,
    mime_type        text,       -- la UI decide imagen vs enlace con esta columna
    size_bytes       bigint not null default 0,
    bucket_id        text not null default 'tickets',
    objeto_id        uuid,
    fecha_subida     timestamptz not null default now()
);
create index idx_adjunto_ticket on public.adjunto (ticket_id);
comment on table public.adjunto is 'Evidencias subidas al bucket de Storage "tickets".';

-- 5. HISTORIAL ------------------------------------------------
-- "cambio" es texto libre a proposito: /update inserta frases; un CHECK romperia la v1.
create table public.historial (
    historial_id     bigint generated always as identity primary key,
    ticket_id        bigint not null references public.ticket (ticket_id) on delete cascade,
    autor_id         bigint references public.usuario (usuario_id),
    campo_modificado varchar(100),   -- /update la inserta; debe existir
    valor_anterior   text,
    valor_nuevo      text,
    cambio           text,
    meta             jsonb,
    fecha_cambio     timestamptz not null default now()
);
create index idx_historial_ticket on public.historial (ticket_id);
comment on table public.historial is
    'Bitacora. La escribe/lee el service role (v1) o triggers (fase 2); sin acceso directo de clientes.';

-- Tablas de la fase 2 (la v1 no las toca) ---------------------

create table public.comentario (
    comentario_id  bigint generated always as identity primary key,
    ticket_id      bigint not null references public.ticket (ticket_id) on delete cascade,
    autor_id       bigint not null references public.usuario (usuario_id),
    tipo           varchar(10) not null
        constraint ck_comentario_tipo check (tipo in ('externo','interno')),
    contenido      text not null,
    adjunto_id     bigint references public.adjunto (adjunto_id) on delete set null,
    fecha_creacion timestamptz not null default now()
);
create index idx_comentario_ticket on public.comentario (ticket_id);

create table public.asignacion (
    asignacion_id    bigint generated always as identity primary key,
    ticket_id        bigint not null references public.ticket (ticket_id) on delete cascade,
    soporte_id       bigint not null references public.usuario (usuario_id),
    fecha_asignacion timestamptz not null default now(),
    activo           boolean not null default true
);
create index idx_asignacion_ticket on public.asignacion (ticket_id);

create table public.prioridad_sla (
    sla_id           bigint generated always as identity primary key,
    prioridad_id     bigint not null unique references public.catalogo (catalogo_id),
    horas_compromiso int not null  -- horas, no una fecha
);

create table public.notificacion (
    notificacion_id bigint generated always as identity primary key,
    destinatario_id bigint not null references public.usuario (usuario_id),
    ticket_id       bigint references public.ticket (ticket_id) on delete cascade,
    tipo            varchar(30) not null
        constraint ck_notificacion_tipo
        check (tipo in ('creacion_ticket','cambio_estado','nuevo_comentario','resuelto','asignacion','actualizacion_usuario')),
    contenido       text not null,
    medio           varchar(10) not null default 'app'
        constraint ck_notificacion_medio check (medio in ('email','app','push')),
    leida           boolean not null default false,
    enviada_en      timestamptz,
    creado_at       timestamptz not null default now()
);
create index idx_notificacion_destinatario on public.notificacion (destinatario_id);
